version: '3.9'
services:
 nginx:
   build: ./nginx
   ports:
     - 1337:80
   volumes:
     - static_volume:/home/app/static
     - media_volume:/home/app/media
   depends_on:
     - web
   restart: "on-failure"
 web:
   build: ./restapi
   command: sh -c "python manage.py makemigrations &&
                   python manage.py migrate &&
                   python manage.py collectstatic --no-input &&
                   gunicorn restapi.wsgi:application --bind 0.0.0.0:8000"
   volumes:
     - static_volume:/home/app/static
     - media_volume:/home/app/media
   expose:
   - 8000
   restart: "on-failure"
volumes:
 static_volume:
 media_volume: